config/urls.py
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", RedirectView.as_view(url="core/home/", permanent=False), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("pesados_el_norte.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("core/", include("pesados_el_norte.core_app.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pesados_el_norte/core_app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from pesados_el_norte.core_app.views.caja import CajaListView

# from pesados_el_norte.users.views import (
#     user_detail_view,
#     user_redirect_view,
#     user_update_view,
# )

app_name = "core"
urlpatterns = [
    path(
        "home/",
        login_required(TemplateView.as_view(template_name="core/home.html")),
        name="home",
    ),
    path(
        "caja/",
        view=CajaListView.as_view(template_name='core/caja.html'),
        name="caja",
    ),
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
]

pesados_el_norte/users/urls.py
from django.urls import path

from pesados_el_norte.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

pesados_el_norte/core_app/models/basemodel.py
from django.db.models import Model, BooleanField, DateTimeField


class BaseModel(Model):
    is_active = BooleanField("is active?", default=True)
    created_at = DateTimeField("created on", auto_now_add=True)
    updated_at = DateTimeField("last modified on", auto_now=True)

    def delete(self, using=None, keep_parents=False):
        self.is_active = False

    delete.alters_data = True

    class Meta:
        abstract = True

pesados_el_norte/core_app/models/payment.py
import uuid
import datetime

from django.db.models import (
    CharField,
    DateField,
    FloatField,
    ForeignKey,
    PositiveIntegerField,
    PROTECT,
    TextField,
    UUIDField,
)
from pesados_el_norte.core_app.models.basemodel import BaseModel
from pesados_el_norte.core_app.models.receipt import Receipt
from pesados_el_norte.users.models import User
from pesados_el_norte.core_app.utils.utils import only_int

ACCOUNTS = (
    ("MACRO", "Banco Macro"),
    ("PATAGONIA", "Banco Patagonia"),
)


class Payment(BaseModel):
    receipt = ForeignKey(Receipt, on_delete=PROTECT, verbose_name="Comprobante")
    date = DateField(default=datetime.date.today, verbose_name="Fecha")
    amount = FloatField(verbose_name="Monto")
    observations = TextField(verbose_name="Observaciones")
    created_by = ForeignKey(User, on_delete=PROTECT, verbose_name="Creado por")

    def __str__(self):
        return f"{self.receipt.date}"

    class Meta:
        abstract = True
        ordering = ["name"]
        verbose_name = "Pago"
        verbose_name_plural = "Pagos"


class Cash(Payment):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return f"$ {self.amount}"

    class Meta:
        ordering = ["date"]
        verbose_name = "Efectivo"
        verbose_name_plural = "Efectivo"


class Check(Payment):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sign_date = DateField(default=datetime.date.today, verbose_name="Fecha Emision")
    pay_date = DateField(default=datetime.date.today, verbose_name="Fecha Cobro")
    number = PositiveIntegerField(verbose_name="Numero")
    cuit = CharField(
        validators=[only_int], max_length=11, unique=True, verbose_name="C.U.I.T."
    )

    class Meta:
        ordering = ["date"]
        verbose_name = "Cheque"
        verbose_name_plural = "Cheques"


class BankTransferReceived(Payment):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number = PositiveIntegerField(verbose_name="Numero")
    account = CharField(
        blank=False,
        choices=ACCOUNTS,
        verbose_name="Cuenta Propia Banco ",
        max_length=100,
    )

    class Meta:
        ordering = ["date"]
        verbose_name = "Transferencia Recibida"
        verbose_name_plural = "Transferencias Recibidas"


class BankTransferIssued(Payment):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number = PositiveIntegerField(verbose_name="Numero")
    account = CharField(
        blank=False,
        choices=ACCOUNTS,
        verbose_name="Cuenta Propia Banco ",
        max_length=100,
    )

    class Meta:
        ordering = ["date"]
        verbose_name = "Transferencia Emitida"
        verbose_name_plural = "Transferencias Emitidas"


class Card(Payment):
    CARDS_TYPES = (
        ("Credito", "Credito"),
        ("Debito", "Debito"),
    )

    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number = PositiveIntegerField(verbose_name="Numero")
    type = CharField(
        blank=False,
        choices=CARDS_TYPES,
        verbose_name="Tipo de Tarjeta",
        max_length=100,
    )

    class Meta:
        ordering = ["date"]
        verbose_name = "Tarjeta"
        verbose_name_plural = "Tarjetas"


class Retentions(Payment):
    RETENTIONS_TYPES = (
        ("IVA", "IVA"),
        ("IIBB", "Ingresos Brutos"),
        ("Gcias", "Ganancias"),
    )

    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number = PositiveIntegerField(verbose_name="Numero")
    retention_type = CharField(
        blank=False,
        choices=RETENTIONS_TYPES,
        verbose_name="Tipo de Retencion",
        max_length=100,
    )

    class Meta:
        ordering = ["date"]
        verbose_name = "Retencion"
        verbose_name_plural = "Retenciones"

pesados_el_norte/core_app/models/person.py
import uuid
from django.db.models import CharField, PositiveIntegerField, UUIDField
from pesados_el_norte.core_app.models.basemodel import BaseModel
from pesados_el_norte.core_app.utils.utils import only_int


class Person(BaseModel):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = CharField(max_length=200, blank=False, verbose_name="Nombre")
    code = PositiveIntegerField(verbose_name="Cod Interno")
    cuit = CharField(
        validators=[only_int], max_length=11, unique=True, verbose_name="C.U.I.T."
    )
    address = CharField(max_length=200, blank=False, verbose_name="Direccion")
    observations = CharField(max_length=200, blank=True, verbose_name="Observaciones")

    def __str__(self):
        return f"{self.name.title}"

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        return super(Person, self).save(*args, **kwargs)

    class Meta:
        ordering = ["name"]
        verbose_name = "Persona"
        verbose_name_plural = "Personas"


class Client(Person):
    class Meta:
        ordering = ["name"]
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"


class Provider(Person):
    class Meta:
        ordering = ["name"]
        verbose_name = "Proveedor"
        verbose_name_plural = "Proveedores"

pesados_el_norte/core_app/models/receipt.py
import uuid
from django.db.models import (
    BooleanField,
    CharField,
    FloatField,
    DateField,
    DateTimeField,
    PositiveIntegerField,
    TextField,
    UUIDField,
    ForeignKey,
    PROTECT,
)
from pesados_el_norte.core_app.models.basemodel import BaseModel
from pesados_el_norte.core_app.models.person import Client, Person, Provider
from pesados_el_norte.users.models import User


class ReceiptType(BaseModel):
    RECEIPT_TYPES = (
        ("Ventas/Recibo", "Ventas / Recibo"),
        ("Compras", "Compras"),
        ("Depositos", "Depositos"),
        ("Gastos", "Gastos"),
        ("Retiros", "Retiros"),
        ("Redondeos", "Redondeos"),
        ("Ingresos", "Ingresos"),
    )
    PERSONS_TYPE = (
        ("Client", Client),
        ("Provider", Provider),
    )
    name = CharField(
        max_length=200,
        verbose_name="Nombre",
    )
    receipt_type = CharField(
        blank=False,
        choices=RECEIPT_TYPES,
        verbose_name="Tipo",
        max_length=100,
    )
    code = PositiveIntegerField(verbose_name="Codigo")
    giver_type = CharField(
        blank=False,
        choices=PERSONS_TYPE,
        verbose_name="Emisor",
        max_length=100,
    )
    receiver_type = CharField(
        blank=False,
        choices=PERSONS_TYPE,
        verbose_name="Receptor",
        max_length=100,
    )

    class Meta:
        verbose_name = "Tipo de Comprobante"
        verbose_name_plural = "Tipos de Comprobantes"


class Receipt(BaseModel):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = DateField(verbose_name="Fecha")
    receipt_type = ForeignKey(ReceiptType, verbose_name="Tipo", on_delete=PROTECT)
    prefix = PositiveIntegerField(verbose_name="Prefijo")
    number = PositiveIntegerField(verbose_name="Numero")
    amount = FloatField(verbose_name="Monto")
    is_cash = BooleanField(verbose_name="Contado?", default=False)
    giver = ForeignKey(
        Person,
        verbose_name="Emisor",
        null=True,
        on_delete=PROTECT,
        related_name="giver",
    )
    receiver = ForeignKey(
        Person,
        verbose_name="Receptor",
        null=True,
        on_delete=PROTECT,
        related_name="receiver",
    )
    approved = BooleanField(verbose_name="Aprobado?", default=False)
    approved_by = ForeignKey(User, verbose_name="Aprobado por", on_delete=PROTECT)
    approved_at = DateTimeField(verbose_name="Fecha aprobacion")
    observations = TextField(verbose_name="Observaciones")

    class Meta:
        verbose_name = "Comprobante"
        verbose_name_plural = "Comprobantes"

# todo Falta el modelo del bonus receipt y migrar

pesados_el_norte/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Pesados El Norte."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

pesados_el_norte/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

pesados_el_norte/core_app/views.py
from django.shortcuts import render

# Create your views here.

pesados_el_norte/core_app/views/caja.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView, ListView
from pesados_el_norte.core_app.models.receipt import Receipt


# User = get_user_model()


class CajaListView(LoginRequiredMixin, ListView):
    model = Receipt
    queryset = Receipt.objects.all()


caja_list_view = CajaListView.as_view()

pesados_el_norte/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

pesados_el_norte/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Pesados El Norte{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Gestion Administrativa">
  <meta name="author" content="Leonardo Hakim">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
  <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
{#    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"#}
{#          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
    <!-- Bootstrap JS and its dependencies-->
    <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
{#    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"#}
{#            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"#}
{#            crossorigin="anonymous"></script>#}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

{#    <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"#}
{#            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"#}
{#            crossorigin="anonymous"></script>#}

    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}

</head>

<body>
{% if user.is_authenticated %}
<div class="mb-1">
  <nav class="navbar navbar-expand-md navbar-light">

    <div class="bg-light logo-home">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static '/images/logo_central_web.jpg' %}" width="150"></a>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:home' %}">{% trans "Home" %}</a>
          </li>
          <li class="nav-item">&nbsp;</li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>
        {% else %}
          {#              <li class="nav-item">#}
          {# URL provided by django-allauth/account/urls.py #}
          {#                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>#}
          {#              </li>#}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endif %}
</div>

<div class="container">

  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
      </div>
    {% endfor %}
  {% endif %}

  <div class="row">
    {% if user.is_authenticated %}
    <div class="col-2 bg-light">
      {% include "core/menu.html" %}
    </div>
    {% endif %}
    <div class="col">
      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    </div>

  </div>

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
  {# Script tags with only code, no src (defer by default) #}
{% endblock inline_javascript %}
</body>
</html>